services:
    whatwedo_search.manager.index:
        class: whatwedo\SearchBundle\Manager\IndexManager
        arguments: ["@doctrine.orm.entity_manager"]

    whatwedo_search.event_listener.index:
        class: whatwedo\SearchBundle\EventListener\IndexListener
        arguments: ["@whatwedo_search.manager.index"]
        tags:
            - { name: doctrine.event_subscriber, connection: default }
